//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InClassVoting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<LearningOutcome> LearningOutcomes { get; set; }
        public virtual DbSet<MatchQuestion> MatchQuestions { get; set; }
        public virtual DbSet<MatchQuestionDone> MatchQuestionDones { get; set; }
        public virtual DbSet<Passage> Passages { get; set; }
        public virtual DbSet<Passage_Done> Passage_Done { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<Poll_Answer> Poll_Answer { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionAnswer> QuestionAnswers { get; set; }
        public virtual DbSet<QuestionAnswerDone> QuestionAnswerDones { get; set; }
        public virtual DbSet<QuestionDone> QuestionDones { get; set; }
        public virtual DbSet<QuestionDoneLO> QuestionDoneLOes { get; set; }
        public virtual DbSet<QuestionLO> QuestionLOes { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<QuizDone> QuizDones { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Answer> Student_Answer { get; set; }
        public virtual DbSet<Student_PollAnswer> Student_PollAnswer { get; set; }
        public virtual DbSet<Student_QuizDone> Student_QuizDone { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    }
}
