//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InClassVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.QuestionAnswers = new HashSet<QuestionAnswer>();
        }
    
        public int QID { get; set; }
        public int ChapterID { get; set; }
        public Nullable<int> PassageID { get; set; }
        public string Text { get; set; }
        public int Qtype { get; set; }
        public Nullable<bool> MixChoice { get; set; }
        public Nullable<bool> GivenWord { get; set; }
        public int Time { get; set; }
        public double Mark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public byte[] ImageData { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual Passage Passage { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; }
    }
}
