//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InClassVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quiz()
        {
            this.QuizDones = new HashSet<QuizDone>();
        }
    
        public int QuizID { get; set; }
        public string QuizName { get; set; }
        public int CourseID { get; set; }
        public string Questions { get; set; }
        public Nullable<int> NumOfQuestion { get; set; }
        public double Mark { get; set; }
        public bool MixQuestion { get; set; }
        public Nullable<int> MixQuestionNumber { get; set; }
        public string Status { get; set; }
        public int Time { get; set; }
        public string QuizType { get; set; }
        public bool PublicResult { get; set; }
        public bool PublicAnswer { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizDone> QuizDones { get; set; }
    }
}
