//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InClassVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_PollAnswer
    {
        public int Student_PollAnsID { get; set; }
        public int Poll_AnswerID { get; set; }
        public int StudentID { get; set; }
    
        public virtual Poll_Answer Poll_Answer { get; set; }
        public virtual Student Student { get; set; }
    }
}
