//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InClassVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_QuizDone
    {
        public int SQID { get; set; }
        public int StudentID { get; set; }
        public int QuizDoneID { get; set; }
        public string ReceivedQuestions { get; set; }
        public string Status { get; set; }
        public double StudentMark { get; set; }
        public double TotalMark { get; set; }
    
        public virtual QuizDone QuizDone { get; set; }
        public virtual Student Student { get; set; }
    }
}
